# external-secret-v2.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: ${KSA_NAMESPACE_V2}
spec:
  secretStoreRef:
    name: gcp-secret-store-v2
    kind: SecretStore
  target:
    name: ${K8S_SECRET_NAME_V2}
    creationPolicy: Owner
  data:
    - secretKey: my-secret-key
      remoteRef:
        key: ${SECRET_NAME_V2}
